forum-app/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="accounts_login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<slug:username>/', views.profile_user,
         name="accounts_profile_user"),
    path('profile/me', views.profile_me, name="accounts_profile_me")
]

forum-app/forum/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('about', views.aboutpage),
    path('', views.homepage),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# python3 manage.py createsuperuser    :tạo user cho trang web admin
# python3 manage.py startapp [name-module(vd: accounts, questión,...)]  :tạo một module

forum-app/questions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.question_list, name="question_list"),
    path('create/', views.question_create, name="question_create"),
    path('<slug:tag_name>/', views.question_list, name="question_tag"),
    path('view/<slug:question_id>/', views.question_detail, name="question_detail"),
    path('edit/<slug:question_id>/',
         views.question_edit, name="question_edit"),
    path('delete/<slug:question_id>/',
         views.question_delete, name="question_delete"),
]

forum-app/questions/models.py
from django.db import models
from django.contrib.auth.models import User


# python3 manage.py makemigrations  :Khởi tạo file migrations tại các module có models
# python3 manage.py migrate         :apply file migrations được tạo từ model vào database
# Create your models here.


class Question(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    tag = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to='images/', blank=True, null=True)
    author = models.ForeignKey(
        User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippetContent(self):
        return self.content[:50] + "..."


class Comment(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(
        User, default=None, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

forum-app/questions/forms.py
from django import forms
from . import models


class CreateQuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = ['title', 'content', 'tag', 'thumbnail']


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content']

forum-app/questions/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from .models import Question
from django.contrib.auth.decorators import login_required
from . import forms
from django.core.paginator import Paginator

# Create your views here.


def question_list(request, tag_name=""):
    q = request.GET.get('q')

    questions = Question.objects.all().order_by(
        'date').reverse()  # lấy tất cả các câu hỏi trong database

    question_top_10 = sorted(
        questions, key=lambda x: x.comments.count(), reverse=True)[:10]  # lấy 10 câu hỏi có nhiều comment nhất

    if tag_name:
        questions = questions.filter(tag__contains=tag_name)

    if q:
        questions = questions.filter(
            title__contains=q)

    question_paginator = Paginator(questions, 6)  # Show 6 questions per page

    page_number = request.GET.get('page')
    page = question_paginator.get_page(page_number)

    context = {
        'page': page,
        'page_range': question_paginator.page_range,
        'tag_name': tag_name,
        'question_top_10': question_top_10
    }
    return render(request, 'questions/question_list.html', context)


def question_detail(request, question_id):
    question = Question.objects.get(id=question_id)

    if request.method == 'POST':
        form = forms.CreateCommentForm(request.POST)
        if form.is_valid():
            # save comment to database
            instance = form.save(commit=False)
            instance.author = request.user
            instance.question = question
            instance.save()
            return HttpResponseRedirect(request.path)
    else:
        form = forms.CreateCommentForm(request.POST)

    return render(request, 'questions/question_detail.html', {'question': question, 'form': form})


def question_edit(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == 'POST':
        form = forms.CreateQuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('accounts:accounts_profile_me')
    else:
        form = forms.CreateQuestionForm(instance=question)
    return render(request, 'questions/question_edit.html', {'form': form, 'question': question})


@login_required(login_url='/accounts/login/')
def question_delete(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.user == question.author:
        question.delete()
        question.save()
    return HttpResponseRedirect('/accounts/profile/me')


@login_required(login_url='/accounts/login/')
def question_create(request):
    if request.method == 'POST':
        form = forms.CreateQuestionForm(request.POST, request.FILES)
        if form.is_valid():
            # save question to database
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return question_list(request)
    else:
        form = forms.CreateQuestionForm(request.POST)
    return render(request, 'questions/question_create.html', {'form': form})

forum-app/questions/templates/questions/question_create.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="card mb-5">
    <div class="card-header">Create new question</div>
    <div class="card-body">
      <form class="form-question-create" action="{% url 'question_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
      </form>
    </div>
  </div>



  <!-- <div class="card">
    <div class="card-header">Comments</div>
    <div class="card-body">
      <div class="form-group green-border-focus">
        <textarea class="form-control" rows="3" placeholder="Write your answer..."></textarea>
        <button class="btn btn-primary mt-2 float-end" type="button">Comment</button>
      </div>
    </div>
  </div> -->
{% endblock %}

forum-app/questions/templates/questions/question_detail.html
{% extends 'base_layout.html' %} {% block content %}
<div class="card">
  <div class="card-header">{{question.title}} - #{{question.tag}}</div>
  <div class="card-body">
    <a class="text-decoration-none" href="{% url 'accounts:accounts_profile_user' username=question.author %}">
      <img class="rounded-circle account-img" width="35" src="{{ question.author.profile.image.url }}" />
      {{question.author}}
    </a>
    {% if question.thumbnail %}
    <div class="container mt-3 d-flex justify-content-center">
      <img src="{{ question.thumbnail.url }}" height="400" />
    </div>
    {% endif %}
    <p class="mt-4">{{question.content}}</p>
    <p>{{question.date}}</p>


  </div>
</div>
<div class="card mt-2">
  <div class="card-header">Comments</div>
  <div class="card-body">

    {% for comment in question.comments.all %}
    <div class="d-flex justify-content-between">
      <h5 class="pl-2">
        <a class="text-decoration-none" href="{% url 'accounts:accounts_profile_user' username=comment.author %}">
          <img class="rounded-circle account-img" width="35" src="{{ comment.author.profile.image.url }}" />
          {{comment.author}}
        </a>
      </h5>
      <i> {{ comment.date }}</i>
    </div>
    <p>{{ comment.content|linebreaks }}</p>
    <hr />
    {% endfor %}

    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'question_detail' question.id %}">
      {% csrf_token %}
      <textarea name="content" class="form-control" rows="3" placeholder="Write your answer..."></textarea>
      <button class="btn btn-primary mt-2 float-end" type="submit" name="button">
        Comment
      </button>
    </form>
    {% else %}
    <div class="alert alert-warning" role="alert">
      Đăng nhập để viết bình luận cho câu hỏi này!
    </div>
    {% endif %}
  </div>

</div>

{% endblock %}

forum-app/questions/templates/questions/question_edit.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="card mb-5">
  <div class="card-header">Update question</div>
  <div class="card-body">
    <form class="form-question-create" action="{% url 'question_edit' question_id=question.id %}" method="post"
      enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Update">
    </form>
  </div>
</div>
{% endblock %}

forum-app/questions/templates/questions/question_list.html
{% extends 'base_layout.html' %} {% block content %}

<!-- Begin Site Title
  ================================================== -->
<div class="container">
  <div class="mainheading text-center">
    <h1 class="sitetitle">~ Forum Learning ~</h1>
    <p class="lead">Share and Learn in the simplest way</p>
  </div>
  <!-- End Site Title
  ================================================== -->

  <!-- Begin Search Question
  ================================================== -->
  <form class="row mb-4 d-flex justify-content-center">
    <div class="col-md-9 mt-2">
      <textarea name="q" class="form-control" rows="2" placeholder="Search question..."></textarea>
    </div>
    <div class="col-md-2 d-grid mt-2">
      <button class="btn btn-success btn-lg" type="submit">
        Search
      </button>
    </div>
  </form>
  <!-- End Search Question
================================================== -->

  <!-- Begin Featured
	================================================== -->
  <div class="row">
    <div class="col-md-3 mb-3">
      <ul class="list-group mt-3">
        <li class="list-group-item active">
          <div class="d-flex justify-content-between">
            <span>Chủ đề</span>
            {% if tag_name != '' %}
            <span class="badge bg-warning d-flex align-items-center">
              <a class="text-decoration-none" href="{% url 'question_list'%}">Bỏ chọn</a>
            </span>
            {% endif %}
          </div>
        </li>
        <li class="list-group-item">
          <a class="page-link" href="{% url 'question_tag' tag_name='khoahoc' %}" aria-label="Previous">
            <span class="sr-only">Khoa học</span>
          </a>
          <a class="page-link" href="{% url 'question_tag' tag_name='lichsu' %}" aria-label="Previous">
            <span class="sr-only">Lịch sử</span>
          </a>
          <a class="page-link" href="{% url 'question_tag' tag_name='thegioi' %}" aria-label="Previous">
            <span class="sr-only">Thế giới</span>
          </a>
          <a class="page-link" href="{% url 'question_tag' tag_name='toanhoc' %}" aria-label="Previous">
            <span class="sr-only">Toán học</span>
          </a>
          <a class="page-link" href="{% url 'question_tag' tag_name='random' %}" aria-label="Previous">
            <span class="sr-only">Random</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 featured-posts">
      <div class="section-title">
        <h2>
          <span>
            {% if tag_name %}
            #{{ tag_name }}
            {% else %}
            New Questions
            {% endif %}
          </span>
        </h2>
      </div>
      <div class="card-columns">
        <div class="row">
          {% for question in page.object_list %}
          <!-- begin post -->
          <div class="col-lg-6 mb-4 question_item_card">
            <div class="card h-100">
              {% if question.thumbnail %}
              <a href="{% url 'question_detail' question_id=question.id %}" class="d-flex justify-content-center p-3">
                <img class="card-img-top" style="width: 250px; height: 100%" src="{{ question.thumbnail.url }}"
                  alt="" />
              </a>
              {% endif %}
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'question_detail' question_id=question.id %}">{{ question.title }}</a>
                </h4>
                <p class="card-text">{{ question.snippetContent }}</p>
                <p>{{ question.date }}</p>
              </div>
            </div>
          </div>
          <!-- end post -->
          {% endfor %}
        </div>
      </div>

      <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
          <a class="page-link" href="{% url 'question_list' %}?page={{ page.previous_page_number }}"
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        {% if page_range.stop > 2 %}
        {% for page_num in page_range %}
        <li class="page-item {% if page.number == page_num %} active {% endif %}">
          <a class="page-link" href="{% url 'question_list' %}?page={{ page_num }}">{{ page_num }}
          </a>
        </li>
        {% endfor %}
        {% endif %}

        {% if page.has_next %}
        <li class="page-item">
          <a class="page-link" href="{% url 'question_list' %}?page={{ page.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>

  <!-- End Featured
  	================================================== -->

  <h4 class="mt-3 mb-3">Top 10 Questions</h4>
  <div class="questions_list mb-5">
    {% for question in question_top_10 %}
    <div class="question_item">
      <h4>
        <a href="{% url 'question_detail' question_id=question.id %}">{{ question.title }}</a>
      </h4>
      <p>{{ question.snippetContent }}</p>
    </div>
    {% endfor %}
  </div>

</div>
{% endblock %}