forum-app/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="accounts_login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/<slug:username>/', views.profile_user,
         name="accounts_profile_user"),
    path('profile/me', views.profile_me, name="accounts_profile_me")
]

forum-app/forum/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('about', views.aboutpage),
    path('', views.homepage),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# python3 manage.py createsuperuser    :tạo user cho trang web admin
# python3 manage.py startapp [name-module(vd: accounts, questión,...)]  :tạo một module

forum-app/templates/aboutpage.html
{% extends 'base_layout.html' %}

{% block content %}
<style>
  body {
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
  }

  html {
    box-sizing: border-box;
  }

  *,
  *:before,
  *:after {
    box-sizing: inherit;
  }

  .column {
    float: left;
    width: 33.3%;
    margin-bottom: 16px;
    padding: 0 8px;
  }

  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    margin: 8px;
  }

  .about-section {
    padding: 50px;
    text-align: center;
    background-color: #474e5d;
    color: white;
  }

  .container {
    padding: 0 16px;
  }

  .container::after,
  .row::after {
    content: "";
    clear: both;
    display: table;
  }

  .title {
    color: grey;
  }

  .button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
  }

  .button:hover {
    background-color: #555;
  }

  @media screen and (max-width: 650px) {
    .column {
      width: 100%;
      display: block;
    }
  }
</style>

<div class="about-section">
  <h1>About Us Page</h1>
  <p>Forum Learning</p>
  <p>Đồ án môn học NT208.M11.ATCL - @UIT - 2021 </p>
</div>

<h2 class="mt-2" style="text-align:center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="/static/images/bao.jpg" alt="bao" style="width:100%">
      <div class="container mt-2">
        <h2>Trịnh Ngọc Bảo</h2>
        <p class="title">Student</p>
        <p>Vì đẹp trai nên tóc anh hai mái.</p>
        <p>19521260@gm.uit.edu.vn</p>
        <p><button class="button">19521260</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/static/images/dang.jpeg" alt="dang" style="width:100%">
      <div class="container mt-2">
        <h2>Đỗ Khánh Đăng</h2>
        <p class="title">Student</p>
        <p>Ông trời tạo ra địa chấn, nụ cười anh là điểm nhấn.</p>
        <p>19521314@gm.uit.edu.vn</p>
        <p><button class="button">19621314</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/static/images/ngocan.jpeg" alt="an" style="width:100%">
      <div class="container mt-2">
        <h2>Lâm Ngọc Ẩn</h2>
        <p class="title">Student</p>
        <p>Kiên trì cũng chính là bền vững.</p>
        <p>19521175@gm.uit.edu.vn</p>
        <p><button class="button">19521175</button></p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

forum-app/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <link rel="stylesheet" href="/static/styles/style.css" />

  <title>Forum Learning</title>
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <div>
        <a class="navbar-brand {% if request.path == '/' %} text-primary {% endif %}" href="/">Home</a>
        <a class="navbar-brand {% if request.path == '/questions/' %} text-primary {% endif %}"
          href="{% url 'question_list' %}">Forum Learning</a>
        <a class="navbar-brand {% if request.path == '/about' %} text-primary {% endif %}" href="/about">About</a>
      </div>
      {% if user.is_authenticated %}
      <div class="d-flex align-items-center">
        <h5 class="navbar-brand">
          <a class="text-decoration-none text-warning" href="{% url 'question_create' %}">+ Question</a>
        </h5>
        <h5 class="navbar-brand">
          <a class="text-decoration-none text-success" href="{% url 'accounts:accounts_profile_me' %}">
            {% if user.profile.image.url %}
            <img width="30px" class="rounded-circle account-img" src="{{ user.profile.image.url }}" />
            {% else %}
            <img width="30px" class="rounded-circle account-img" src="https://dummyimage.com/100x100" />
            {% endif %}
          </a>
        </h5>
        <h5 class="navbar-brand">
          <a class="text-decoration-none text-danger" href="{% url 'accounts:logout' %}">
            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd">
              <path d="M24 22h-20v-7h2v5h16v-16h-16v5h-2v-7h20v20zm-13-11v-4l6 5-6 5v-4h-11v-2h11z" />
            </svg>
          </a>
        </h5>
      </div>
      {% else %}
      <div class="d-flex">
        <h5 class="navbar-brand">
          <a class="text-decoration-none" href="{% url 'accounts:signup' %}">Signup</a>
        </h5>
        <h5 class="navbar-brand">
          <a class="text-decoration-none" href="{% url 'accounts:accounts_login' %}">Login</a>
        </h5>
      </div>
      {% endif %}
    </div>
  </nav>
  <div class="container">
    <div class="mt-3">{% block content %} {% endblock %}</div>
  </div>

  <!-- Begin Footer
	================================================== -->
  <div class="footer">
    <p class="pull-left">Copyright &copy; 2021</p>
    <p class="pull-right">Forum Leaning by Team Đăng | Bảo | Ẩn</p>
  </div>
  <!-- End Footer
	================================================== -->


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>
</body>

</html>

forum-app/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="hero d-flex align-items-center">

  <div class="row">
    <div class="col-lg-6 d-flex flex-column justify-content-center">
      <h1 data-aos="fade-up">Welcome to the Knowledge hub! What kind of knowledge do you want to share?</h1>
      <h4 data-aos="fade-up" data-aos-delay="400">The most efficient way to enrich your own world of knowledge is to
        accumulate it by internalizing new things from people around the globe. And this is your first start to do it.
      </h4>
      <div data-aos="fade-up" data-aos-delay="600">
        <div class="text-center text-lg-start">
          <a href="/questions"
            class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center text-decoration-none">
            <span>Go to forum</span>
            <i class="bi bi-arrow-right"></i>
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
      <img src="/static/images/hero-img.png" class="img-fluid" alt="">
    </div>
  </div>

</section>
<!-- End Hero -->

<!-- ======= About Section ======= -->
<section id="about" class="about">

  <div data-aos="fade-up">
    <div class="row gx-0">

      <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
        <div class="content">
          <h3>What is this website about?</h3>
          <h2></h2>
          <p>
            If you want to know the unknown things that are not commonly taught by teachers at school or simply you
            cannot find a honest or suitable answer on google, you are free to ask anyone in the forum and maybe, you
            will figure out what you want to know.
            Also, you can share what kind of knowledge you are holding to people in this place to trade for newly
            amazing things from others in the comment section of your post.
          </p>
          <div class="text-center text-lg-start">
            <a href="/about"
              class="btn-read-more d-inline-flex align-items-center justify-content-center align-self-center text-decoration-none">
              <span>About Us</span>
              <i class="bi bi-arrow-right"></i>
            </a>
          </div>
        </div>
      </div>

      <div class="col-lg-6 d-flex align-items-center" data-aos="zoom-out" data-aos-delay="200">
        <img src="static/images/about.jpg" class="img-fluid" alt="">
      </div>

    </div>
  </div>

</section>
<!-- End About Section -->

<!-- ======= Values Section ======= -->
<section id="values" class="values pt-5">

  <div data-aos="fade-up">

    <header class="section-header">
      <h2>Our Values</h2>
      <p>These are 3 important points we are heading to</p>
    </header>

    <div class="row">

      <div class="col-lg-4">
        <div class="box" data-aos="fade-up" data-aos-delay="200">
          <img src="static/images/values-1.png" class="img-fluid" alt="">
          <h3>Comprehensive understanding</h3>
        </div>
      </div>

      <div class="col-lg-4 mt-4 mt-lg-0">
        <div class="box" data-aos="fade-up" data-aos-delay="400">
          <img src="static/images/values-2.png" class="img-fluid" alt="">
          <h3>Discovering new land of knowledge</h3>
        </div>
      </div>

      <div class="col-lg-4 mt-4 mt-lg-0">
        <div class="box" data-aos="fade-up" data-aos-delay="600">
          <img src="static/images/values-3.png" class="img-fluid" alt="">
          <h3>New friends, new connection, new knowledges</h3>
        </div>
      </div>

    </div>

  </div>

</section><!-- End Values Section -->
{% endblock %}